### ISSUE TITLE
separate {required,optional} per-{pheno,assoc,variant} data, and allow adding more in `config.py`

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#57]
## TODO:

- [x] make test phenotypes with each of [`MAF`, `AF`, `AC` , none].

    ```
    for f in ~/PROJECTS/pheweb/test/input_files/assoc-files/*;do echo "=> $f"; zcat "$f"|head -2|ptrcolumn;echo;done
    ```

- [x] add `af` and `ac` to `per_assoc_fields`.

- [x]  make `utils.get_maf(variant, pheno)` which tries `maf`, `af`, `ac` (which only works if `num_samples` or `num_cases`+`num_controls`).  Use it for `minimum_maf` and `qq`.

- [x] `matrixify`
    - I added the constraint that all `per-variant` fields must be present and identical in all phenotypes.

- [x] on `variant.html`, show avg&range of  MAF/AF/AC.

- [ ] add `R2` and `callrate` to `per_assoc_fields` in `test/data_dir/config.py`.

**Comment by pjvandehaar** [comment]
(`assoc_file_parser` really ought to be a class.  It's not that hard to make my own `__iter__()`.)

- [ ] handle cases where `maf` is missing, or we only have `af`.
    - `qq` should make its own `maf` from `af` if available, or else just don't do `maf`-stratifying.
- [ ] remove averaging of MAF in matrixify.cpp.
    - `matrixify` will need to know which fields are per-variant vs per-association.  Maybe pass them in per-variant fields comma-separated as argv[1] and assume all others are per-association.

- [ ] `input_file_parser` 
- [ ] `get-cpras` should use `assoc_file_parser.get_fieldnames_and_variants(..., cpra_only=True)`.

**Comment by pjvandehaar** [comment]
If these were ordered, like
```
possible_fields = {
  'per-variant': [
    ('chrom', {
        'aliases': ['#CHROM'],
        'type': str,
        'required': True,
    }), ...
  ],
}
```
then could what would I need to use these to auto-generate tooltips?
- region LZ and Manhattan would show `per-variant` attributes.
- PheWAS would show `per-assoc` and also `per-pheno` attributes.
    - where do we manage our `per-pheno` attributes?  Where should we?
- all optional attributes would be wrapped in `{{#if ...}}{{/if}}`.
- people could override `.tooltip_line_template` with a string or make it `false`.
    - eg, 

        ```
        beta: {
            tooltip_line_template: '{{#if beta}}beta: <strong>{{beta}}{{#if sebeta}} ({{sebeta}}){{/if}}<br/>{{/if}}`
        },
        sebeta: {
            tooltip_line_template: false
        }
        ```

**Comment by pjvandehaar** [comment]
What sorts of `per-variant` fields are we going to have?
- core: `chrom`,`pos`,`ref`,`alt`
- added by PheWeb: `rsid`, `nearest_genes`
- user's choice: `af`/`maf` can be per-variant or per-assoc, and then we'll assert they're the same for all phenos and handle either case downstream.
- importable from VEP: ???
- imputation quality
- indel vs SNP

ie, there are two types:
- per-variant fields that must be in every phenotype and match perfectly.
- per-variant fields that will be read from an annotations file (like VEP).

**Comment by pjvandehaar** [comment]
Deal with `utils.py::pheno_fields_to_include_with_variant`
